"""Page 6: Alerts Center — Price drops, stockouts, entrants filterable."""
import streamlit as st
import pandas as pd
import plotly.express as px
from utils.db import fetch, latest_snapshot_date, get_asins_with_metadata

st.set_page_config(page_title="Alerts Center", page_icon="🚨", layout="wide")

st.title("🚨 Alerts Center")
st.caption("All alerts generated by the analytics pipeline — filterable")

latest = latest_snapshot_date()
asins_meta = get_asins_with_metadata()

# --- Severity metrics ---
alerts = fetch("alerts", order_col="snapshot_date", limit=10000)
if alerts:
    df = pd.DataFrame(alerts)
    df["product"] = df["asin"].map(lambda a: asins_meta.get(a, {}).get("product_name", a)[:40] if a else "—")

    today_df = df[df["snapshot_date"] == latest]
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Today", len(today_df))
    c2.metric("🔴 High", sum(today_df["severity"] == "high"))
    c3.metric("🟡 Medium", sum(today_df["severity"] == "medium"))
    c4.metric("🟢 Low", sum(today_df["severity"] == "low"))

st.divider()

# --- Filters ---
col1, col2, col3 = st.columns(3)
with col1:
    date_filter = st.date_input("Date", value=pd.to_datetime(latest))
with col2:
    alert_types = df["alert_type"].unique().tolist() if alerts else []
    type_filter = st.multiselect("Type", alert_types, default=alert_types)
with col3:
    severities = ["high", "medium", "low"]
    sev_filter = st.multiselect("Severity", severities, default=severities)

# --- Alert counts by type (timeline) ---
st.subheader("Alert Timeline")
if alerts:
    timeline = df.groupby(["snapshot_date", "alert_type"]).size().reset_index(name="count")
    fig = px.bar(timeline, x="snapshot_date", y="count", color="alert_type",
                title="Alerts over time (by type)")
    st.plotly_chart(fig, use_container_width=True)

st.divider()

# --- Filtered alert table ---
st.subheader("📋 Alert Log")
if alerts:
    filtered = df[
        (df["snapshot_date"] == str(date_filter)) &
        (df["alert_type"].isin(type_filter)) &
        (df["severity"].isin(sev_filter))
    ]
    if not filtered.empty:
        # Color rows by severity
        def color_sev(row):
            color = {"high": "background-color: #fecaca",
                    "medium": "background-color: #fef3c7",
                    "low": "background-color: #d1fae5"}.get(row["severity"], "")
            return [color] * len(row)

        display_df = filtered[["product", "alert_type", "severity", "message"]]
        st.dataframe(display_df.style.apply(color_sev, axis=1),
                    hide_index=True, use_container_width=True)
    else:
        st.info("Không có alert phù hợp filter.")
